module.exports = {
  moduleFileExtensions: ['js', 'json', 'ts'],
  rootDir: '.',
  testRegex: 'test/.*\\.(e2e-)?spec\\.ts$',
  transform: {
    '^.+\\.(t|j)s$': 'ts-jest',
  },
  testEnvironment: 'node',
  collectCoverage: true,
  collectCoverageFrom: [
    'src/modules/auth/bearer-token.ts',
    'src/modules/auth/supabase-auth.guard.ts',
    'src/modules/auth/supabase-auth.service.ts',
    'src/modules/auth/supabase-request-client.service.ts',
    'src/modules/user/user.service.ts',
    'src/modules/chat/chat.controller.ts',
    'src/modules/chat/chat.errors.ts',
    'src/modules/chat/chat-pagination.ts',
    'src/modules/chat/chat.service.ts',
    'src/modules/chat/chat.repository.ts',
    'src/modules/chat/chat.types.ts',
    'src/modules/ai/chat-rate-limit.service.ts',
  ],
  coverageReporters: ['text', 'text-summary', 'json-summary'],
  coverageThreshold: {
    global: {
      branches: 75,
      functions: 95,
      lines: 90,
      statements: 90,
    },
    './src/modules/auth/supabase-auth.guard.ts': {
      branches: 90,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    './src/modules/chat/chat.controller.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    './src/modules/chat/chat.errors.ts': {
      branches: 90,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    './src/modules/chat/chat-pagination.ts': {
      branches: 90,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    './src/modules/chat/chat.repository.ts': {
      branches: 85,
      functions: 100,
      lines: 100,
      statements: 90,
    },
    './src/modules/chat/chat.service.ts': {
      branches: 90,
      functions: 100,
      lines: 100,
      statements: 100,
    },
  },
};
